#!/bin/sh

# A working btrfs mount point - any will do as long as root have write access
ZFS_ROOT=p0/subutai

# A folder which is used exclusively for this - can NOT exist and WILL
# be cleaned out when done!
ZFS_BUILD=build

# Set base
BASE=bullseye
REP=http://deb.debian.org/debian/

# Repos
REPOS=$(cat <<'END_HEREDOC'
deb http://deb.debian.org/debian/ bullseye main contrib non-free
deb http://deb.debian.org/debian/ bullseye-updates main contrib non-free
deb http://deb.debian.org/debian bullseye-backports main contrib non-free
END_HEREDOC
)

# Extra base packages to be installed
EXTRA=openssh-server,openssh-client,iputils-ping,vim,less,python

# Name of resulting template
NAME=debian-bullseye
VERSION=$(git describe --abbrev=0 --tags)
OWNER=subutai

. ./build-template

# vim: ts=4 et nowrap autoindent
