#!/bin/sh

# A working btrfs mount point - any will do as long as root have write access
BTRFS_ROOT=/var/snap/subutai-master/common/lxc

# A folder which is used exclusively for this - can NOT exist and WILL
# be cleaned out when done!
BTRFS_BUILD=build

# Set base
BASE=stable
REP=http://deb.debian.org/debian/

# Repos
REPOS=$(cat <<'END_HEREDOC'
deb http://httpredir.debian.org/debian/ stretch main contrib non-free
deb http://httpredir.debian.org/debian/ stable-updates main contrib non-free
deb http://httpredir.debian.org/debian stretch-backports main contrib non-free
deb http://security.debian.org/debian-security stretch/updates main
END_HEREDOC
)

# Extra base packages to be installed
EXTRA=openssh-server,openssh-client,iputils-ping,vim,less

# Name of resulting template
NAME=debian-stretch
VERSION=0.2.1

. ./build-template

# vim: ts=4 et nowrap autoindent
