# 
# Makefile for building Subutai Base Templates
#


# Settings
ZPOOL=subutai
ZFS_BUILD=build
NAME=debian-stretch
VERSION=0.4.0
OWNER=lbthomsen
BASE=stable
REP=http://deb.debian.org/debian/
EXTRA=openssh-server,openssh-client,iputils-ping,vim,less,python

include inc/build.mk

# vim: ts=8 nowrap autoindent
