# 
# Makefile for building Subutai Base Templates
#


# Settings
ZPOOL=subutai
ZFS_BUILD=build
NAME=debian-stretch
VERSION=0.4.0
OWNER=lbthomsen
BASE=stable

include inc/build.mk

# vim: ts=8 nowrap autoindent
