#!/bin/sh

# A working btrfs mount point - any will do as long as root have write access
BTRFS_ROOT=/var/snap/subutai-master/common/lxc

# A folder which is used exclusively for this - can NOT exist and WILL
# be cleaned out when done!
BTRFS_BUILD=build

# Set base
BASE=xenial
REP=http://archive.ubuntu.com/ubuntu/

# Repos
REPOS=$(cat <<'END_HEREDOC'
deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse
#deb http://us.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu xenial-security main restricted universe multiverse
deb http://ppa.launchpad.net/x2go/stable/ubuntu xenial main
END_HEREDOC
)

# Extra base packages to be installed
EXTRA=openssh-server,openssh-client,iputils-ping,less,vim

# Install with full repos
PKGS="x2goserver mate-desktop mate-session-manager"

# Name of resulting template
NAME=mate2go
VERSION=0.0.2

. ./build-template

# vim: ts=4 et nowrap autoindent
