#!/bin/sh

# A working btrfs mount point - any will do as long as root have write access
ZFS_ROOT=p0/subutai

# A folder which is used exclusively for this - can NOT exist and WILL
# be cleaned out when done!
ZFS_BUILD=build

# Set base
BASE=bionic
REP=http://archive.ubuntu.com/ubuntu/

# Repos
REPOS=$(cat <<'END_HEREDOC'
deb http://us.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu bionic-security main restricted universe multiverse
END_HEREDOC
)

# Extra base packages to be installed
EXTRA=openssh-server,openssh-client,iputils-ping,less,vim,python,python3

# Install with full repos
#PKGS=vim

# Name of resulting template
NAME=ubuntu-bionic
VERSION=$(git describe --abbrev=0 --tags)
OWNER=lbthomsen

. ./build-template

# vim: ts=4 et nowrap autoindent
