#!/bin/sh

# A working btrfs mount point - any will do as long as root have write access
BTRFS_ROOT=/var/snap/subutai-master/common/lxc

# A folder which is used exclusively for this - can NOT exist and WILL
# be cleaned out when done!
BTRFS_BUILD=build

# Set base
BASE=xenial
REP=http://archive.ubuntu.com/ubuntu/

# Repos
REPOS=$(cat <<'END_HEREDOC'
deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted
deb http://us.archive.ubuntu.com/ubuntu/ xenial universe
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe
deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
#deb http://us.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu xenial-security main restricted
deb http://security.ubuntu.com/ubuntu xenial-security universe
deb http://security.ubuntu.com/ubuntu xenial-security multiverse
END_HEREDOC
)

# Extra base packages to be installed
EXTRA=openssh-server,openssh-client,iputils-ping,vim,less

# Name of resulting template
NAME=ubuntu-xenial
VERSION=0.1.9

. ./build-template

# vim: ts=4 et nowrap autoindent
