#!/bin/sh

# A working btrfs mount point - any will do as long as root have write access
BTRFS_ROOT=/var/snap/subutai-master/common/lxc

# A folder which is used exclusively for this - can NOT exist and WILL
# be cleaned out when done!
BTRFS_BUILD=build

# Set base
BASE=bionic
REP=http://archive.ubuntu.com/ubuntu/

# Repos
#REPOS=$(cat <<'END_HEREDOC'
#deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
#deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
#deb http://security.ubuntu.com/ubuntu bionic-security main restricted universe multiverse
#END_HEREDOC
#)

# Extra base packages to be installed
EXTRA=openssh-server,openssh-client,iputils-ping,vim,less

# Name of resulting template
NAME=ubuntu-bionic
VERSION=0.1.1

. ./build-template

# vim: ts=4 et nowrap autoindent
